title: PuR3 S0uL
description: Blogs and WriteUps
theme: just-the-docs
color_scheme: dark

url: https://pur3-s0ul.github.io/s1teTesting/

aux_links:
  Template Repository: https://github.com/pur3-S0uL/s1teTesting/
